// <auto-generated />
using dvcsharp_core_api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace dvcsharpcoreapi.Migrations
{
    [DbContext(typeof(GenericDataContext))]
    [Migration("20180514042927_AddPasswordRestRequest")]
    partial class AddPasswordRestRequest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("dvcsharp_core_api.Models.PasswordResetRequest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("email");

                    b.Property<string>("key");

                    b.Property<string>("password");

                    b.Property<string>("passwordConfirmation");

                    b.Property<DateTime>("updatedAt");

                    b.HasKey("ID");

                    b.ToTable("PasswordResetRequests");
                });

            modelBuilder.Entity("dvcsharp_core_api.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("name")
                        .IsRequired();

                    b.Property<string>("password")
                        .IsRequired();

                    b.Property<string>("role")
                        .IsRequired();

                    b.Property<DateTime>("updatedAt");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
